`timescale 1ns/1ps

module tb_simd4x8_c_ref;
    logic clk = 1'b0;
    logic rst_n = 1'b0;
    logic start = 1'b0;
    logic [31:0] a = '0;
    logic [31:0] b = '0;
    logic [63:0] acc = '0;
    logic comb_busy, comb_done, iter_busy, iter_done;
    logic [63:0] comb_result, iter_result;
    logic [63:0] expected;
    integer vector_file;
    integer scan_status;
    integer vector_count;
    reg [1023:0] vector_path;

    simd4x8_mac_comb_top comb (.*,
        .busy(comb_busy), .done(comb_done), .result(comb_result));
    simd4x8_mac_iter_top iter (.*,
        .busy(iter_busy), .done(iter_done), .result(iter_result));

    always #5 clk = ~clk;

    task automatic check_vector;
        input logic [31:0] vector_a;
        input logic [31:0] vector_b;
        input logic [63:0] vector_acc;
        input logic [63:0] vector_expected;
        begin
            @(negedge clk);
            a = vector_a;
            b = vector_b;
            acc = vector_acc;
            start = 1'b1;
            @(negedge clk);
            start = 1'b0;

            wait (comb_done);
            #1 assert (comb_result == vector_expected)
                else $fatal(1, "comb VMAC mismatch at vector %0d", vector_count);
            assert (!comb_busy) else $fatal(1, "comb VMAC busy at vector %0d", vector_count);

            wait (iter_busy);
            @(posedge iter_done);
            #1 assert (iter_result == vector_expected)
                else $fatal(1, "iter VMAC mismatch at vector %0d", vector_count);
            assert (!iter_busy) else $fatal(1, "iter VMAC busy at vector %0d", vector_count);
        end
    endtask

    initial begin
        if (!$value$plusargs("vectors=%s", vector_path))
            $fatal(1, "supply +vectors=PATH generated by vmac_vector_gen");
        vector_file = $fopen(vector_path, "r");
        if (vector_file == 0)
            $fatal(1, "cannot open vector file %0s", vector_path);

        repeat (2) @(posedge clk);
        rst_n = 1'b1;
        vector_count = 0;
        while (!$feof(vector_file)) begin
            scan_status = $fscanf(vector_file, "%h %h %h %h\n", a, b, acc, expected);
            if (scan_status == 4) begin
                check_vector(a, b, acc, expected);
                vector_count = vector_count + 1;
            end else if (scan_status != -1) begin
                $fatal(1, "malformed vector file near vector %0d", vector_count);
            end
        end
        $fclose(vector_file);
        assert (vector_count == 132) else $fatal(1, "unexpected vector count: %0d", vector_count);
        $display("SIMD4x8 C-reference RTL test passed: %0d vectors", vector_count);
        $finish;
    end
endmodule
